### ISSUE TITLE
Further simplify message view

### ISSUE THREAD

**Issue by Muffo** [boukestam/inbox-in-gmail#34] opened 2019-04-10 18:30 UTC
A number of elements displayed in the message view are redundant and could be removed.
I highlighted them in yellow:

![image](https://user-images.githubusercontent.com/538925/55904071-e1e16800-5b83-11e9-9912-b916a78f729e.png)

Most (all?) of them were not displayed in the original Inbox. If the user really needs them, they are still available in the menu marked in green.

**Comment by joeytroy** [comment] 2019-04-10 18:42
@Muffo looking at this it doesn't make sense to remove them. Yes a lot of the items can be completed under the bread crumb menu but a lot of users also like having a quick click button instead of access a menu with a click and then click again. For me I prefer it, yes Inbox didn't offer that but too me 1 click beats 2 clicks. I will let @boukestam or @russelldc weigh in.

**Comment by russelldc** [comment] 2019-04-10 18:43
@boukestam What do you think? I'm all for removing redundancy if the whole point of this extension is returning the interface to the simplicity of Inbox. This doesn't remove any functionality, it just cleans the UI.

I'm likely biased because I would almost never use **any** of those highlighted features.

**Comment by russelldc** [comment] 2019-04-10 18:47
Also, if it's so contentious, this could be toggled in the extension's options.

**Comment by boukestam** [comment] 2019-04-10 18:55
The buttons above act on the entire chain of emails. The ellipsis button acts on an individual email. So there is definitely a difference between those buttons. The question is which features get used by people and will annoy users when we remove it. If the problem is that those buttons are distracting then maybe we should change the opacity or figure out another way to fix the underlying problem without removing those features

**Comment by russelldc** [comment] 2019-04-10 18:58
> The question is which features get used by people and will annoy users when we remove it.

I don't understand this argument. The vast majority, if not all of the users of this extension are only using it because they just got kicked off Inbox. These features wouldn't be familiar to them, anyway.

Again though, if we're going to be cautious on that front, I'm not advocating for removing the features, just the redundant buttons.

**Comment by joeytroy** [comment] 2019-04-10 19:06
@russelldc the bigger question is how many truly remember inbox as it was lol. I mean now that we have all been thrown back to "gmail land" there is some things I don't recall. Honestly I don't think we will ever make gmail work like inbox did but as the extension is today it feels much better than going back to gmail. Sadly I think if we started collaborating right after the news hit about the demise of inbox we might be in a better place. For me personally it doesn't cause more confusion with the extra buttons and out of 1500+ users we have one open issue.

**Comment by boukestam** [comment] 2019-04-10 19:12
I agree that we should focus on users coming from inbox. But me personally use the report spam button above the email quite often. What I'm trying to say I guess is that it's really hard to predict what other users do, even those coming from inbox, they probably have used gmail before or use one of those buttons to replace a feature of inbox (like the grouping of emails which is really hard for us to do). But we can experiment with removing some things that we are 99% sure don't get used by anyone and are really annoying

**Comment by russelldc** [comment] 2019-04-10 19:14
How about just the elements highlighted by @Muffo on the email itself?

I agree dealing with the upper toolbar is tricky because it's the same one that deals with multiple checked emails from the email list/inbox page. There wouldn't be much of a visual difference to get rid of those anyway.

**Comment by joeytroy** [comment] 2019-04-10 19:17
Which buttons are we exactly talking about?

![image](https://user-images.githubusercontent.com/1558465/55907084-042eb200-5b93-11e9-80b9-fd92553761b7.png)

**Comment by russelldc** [comment] 2019-04-10 19:18
@g60madman The ones on the email card, not in the toolbar.

**Comment by joeytroy** [comment] 2019-04-10 19:19
So are you then saying 1-6? Or just a handful of them?

![image](https://user-images.githubusercontent.com/1558465/55907186-4952e400-5b93-11e9-9bc1-5363288da4c8.png)

**Comment by russelldc** [comment] 2019-04-10 19:20
As @Muffo explained, remove the yellow highlighted elements because the green highlighted dropdowns already contain those features.

**Comment by russelldc** [comment] 2019-04-10 19:21
For example, here's how one of my recent emails would look with these changes. I also reduced the left-padding of the email subject line to better reflect Inbox's style (and because it was oddly spaced as it was).

<img width="1362" alt="Screen Shot 2019-04-10 at 8 19 25 PM" src="https://user-images.githubusercontent.com/5100126/55907262-2abe0e80-5bce-11e9-9775-149864674ac9.png">

For rough reference, here's a blurry screenshot I found of an open email in Inbox:

<img width="392" alt="Screen Shot 2019-04-10 at 8 23 07 PM" src="https://user-images.githubusercontent.com/5100126/55907395-8ee0d280-5bce-11e9-8b53-1872547b7c89.png">

**Comment by joeytroy** [comment] 2019-04-10 19:24
@russelldc I think it looks good to me. You got my vote!

**Comment by Muffo** [comment] 2019-04-10 20:07
That would work great! 👍

**Comment by russelldc** [comment] 2019-04-11 21:23
@Muffo Please close this one as well, when you get a chance. It's up for PR (#43) at the moment.

**Closed as completed** 2019-04-11 21:35 UTC
Labels: enhancement
