### ISSUE TITLE
Any chance of bundling?

### ISSUE THREAD

**Issue by jcgoble3** [boukestam/inbox-in-gmail#37] opened 2019-04-10 20:27 UTC
The major critical feature from Inbox that is missing in Gmail for me is bundling by label. I don't mean the default inbox categories (Social, Promotions, etc.); I mean the ability to tell it "I want all emails with this arbitrary label that are in my inbox to be collapsed into one line that I can click on to expand the list". My inbox is completely unmanageable without these bundles.

Is there any chance of getting this feature? I would not mind at all having to dig into a separate extension settings screen to manually type in and manage which labels I want bundled if that's what it takes. This is literally the make-or-break feature of Inbox for me, and the reason I am postponing Windows updates because I refuse to close my Inbox tab until I am forced to. I use Firefox, if that matters.

**Comment by abasiri** [comment] 2019-04-11 01:02
I'm playing around with a way to do bundling that would only affect the emails on the current page. It's very complicated and you'd have to keep in mind that it would only affect the currently visible 50 emails on the page. If there are other pages, then they are not going to be bundled correctly into the current page.

The other issue is that the page would every once in a while "flash". That is emails would get unbundled and quickly (in less than a second) get bundled again. I haven't been able to overcome this issue, as the extension won't have control over when gmail tries to redraw the page, all we can do is try to bundle things up again as fast as possible afterwards.

**Comment by jcgoble3** [comment] 2019-04-11 02:11
That would be fine with me. I don't keep 50 emails in my inbox, just what I need to follow up on and refer to (mostly stuff about multiple school events and ceremonies at the moment because I'm approaching graduation with honors next month).

The flash is something I would gladly put up with to get my bundling back, but I wonder if it's possible to monkeypatch Google's own redraw code to avoid it.

**Comment by abasiri** [comment] 2019-04-11 05:27
That would probably require more time and knowledge than what I have :) But yes, the bundling was the most important feature for me also.

**Comment by jcgoble3** [comment] 2019-04-16 23:52
Any progress on this? My computer is getting increasingly slow and unstable after over a month without a reboot, and I fear it may crash soon. If you have a working prototype of this, feel free to point me to it, as I would be happy to test it and offer feedback. I use Firefox and would just need the packaged extension file to sideload (doesn't need to be on the add-on store).

**Comment by abasiri** [comment] 2019-04-27 06:52
So far all attempts at this have been total disasters :) I'll keep trying.

**Comment by russelldc** [comment] 2019-04-27 18:44
@abasiri  @jcgoble3 

Michael Leggett, the co-creator/designer of Inbox, seems to think it's possible. Here's what he mentioned in an issue on his recently released Gmail simplifying extension:
https://github.com/leggett/simplify/issues/56

After finding [that gmail.js library](https://github.com/KartikTalwar/gmail.js/) we talked about in one of the other issues, I think it is, too.

**Comment by abasiri** [comment] 2019-04-27 19:46
I have a prototype that pulls the emails with same labels and groups them
together in the right place. The problem is that I can't figure out a way
to manage the eventlisteners. The listeners are set using closures and
without managing some of them correctly, things behave really badly. I'll
keep trying, we'll see. If also need help with css polish if I make more
progress

**Comment by Muffo** [comment] 2019-04-27 20:15
Out of curiosity, what are the listeners used for? What events are they responding to?

**Comment by russelldc** [comment] 2019-04-27 20:16
@abasiri I wonder if it's possible to not just do this based on labels, but instead the category Gmail would have put it in (Primary, Social, Promotions, Updates, Forum)

Gmail.js seems to have a lot of helpers for event listeners

**Comment by abasiri** [comment] 2019-04-27 20:28
My personal interest is in getting the labels working as I have my own
labels. The categories don't really solve a problem for me, so I'm biased.

**Comment by russelldc** [comment] 2019-04-27 20:31
@abasiri Yup, not a problem, it was what @jcgoble3 was asking for when he created this issue, after all.

I just think at least at some point in the future, the extension should be able to handle those default categories as well, for the majority of people who don't use manual labelling.

**Comment by jcgoble3** [comment] 2019-04-27 20:35
I don't disagree that bundling by the default categories would be useful for many people, and indeed it should be worked on, but as implied by my initial post here, I don't use them at all and instead rely on a crap ton of custom filters that produce automatic labels, some of which I want to see in bundles.

I also don't care about how it looks, as long as it works. I'll take something that does exactly what I want it to do but looks terrible over something that only comes close to what I want but looks beautiful every time.

**Comment by russelldc** [comment] 2019-04-27 20:40
So that those two workflows wouldn't conflict, it seems like a feature that would end up as an extension option, using the option menu started by abasiri in PR #61 for changing how reminders are handled.

**Comment by abasiri** [comment] 2019-04-27 22:46
There is an option in Gmail to have the categories show up as labels. That
should resolve both use cases.

**Comment by leggett** [comment] 2019-04-29 23:38
Hey gang... the way I was thinking of it was to insert my own row for a bundle and link that to the search for that label (update the url hashtag). Expanding it inline is likely not going to work and this way you get all the emails for the label, not just the ones in the inbox (though you could link to "label:x in:inbox") if you wanted to only show the ones in the inbox. 

You can do the same for the categories. Also note that the category tabs allow you to have up to 500 threads in the DOM at once (they are all loaded but only one tab is shown at a time). I've been forcing my Forums tab to act almost like a second inbox with a few different labels that get a lot of mail going there.

**Comment by jcgoble3** [comment] 2019-04-30 00:30
> (though you could link to "label:x in:inbox") if you wanted to only show the ones in the inbox.

This would be mandatory for my workflow. Currently in my still-open Inbox tab, I have, among others, a bundle for the "college stuff" label containing a few emails, some dating back to the beginning of spring semester, that I keep in the inbox because I need to refer to them. However, everything sent to either of my school emails (I have two because I'm getting ready to transfer) is auto-forwarded to Gmail and auto-labeled in Gmail with "college stuff". That is hundreds of emails per semester, the majority of which is glanced at and marked "done".

A search for only the label would make it next to impossible to quickly retrieve the early-semester emails that I still need when I need them. The search would absolutely have to be filtered to inbox only to avoid burying those older emails.

**Comment by abasiri** [comment] 2019-04-30 00:53
I really like this idea and I should be able to prototype it quickly, if it's trivial to trigger the search.

It might be a couple of days before I get a chance to do this though, really busy week ahead of me

**Comment by abasiri** [comment] 2019-04-30 04:33
I decided to procrastinate on other work and ended up working on this a bit. Can a few folks try the version in the PR and let me know what issues you find.

Work that still needs to be done:
* Ability to turn on and off using extension options
* Highlighting as read/unread depending on emails being bundled.
* Will entry correctly disappear if underlying emails are archived

![image](https://user-images.githubusercontent.com/708414/56940965-4a0dd480-6ac6-11e9-926d-ae59aab27914.png)

**Comment by jcgoble3** [comment] 2019-04-30 04:37
Nice! I've shut down my computers for the night but will experiment with it tomorrow after classes.

**Comment by russelldc** [comment] 2019-04-30 13:31
@jcgoble3 It's quite glitchy right now, I certainly wouldn't recommend losing your Inbox tab for it yet!

**Comment by jcgoble3** [comment] 2019-04-30 13:32
@russelldc I just saw your comments on the PR, so I'll wait a bit.

**Comment by russelldc** [comment] 2019-05-03 15:41
I'll go ahead and close this now that the PR looks like it's about to be merged.

**Closed as completed by russelldc** 2019-05-03 15:41 UTC
Labels: enhancement
